# Generated by Django 4.2.10 on 2024-02-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegrambot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
