# Generated by Django 4.2.10 on 2024-02-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
    ]
